services:
  flaskapp:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
    env_file:
      - .env
    environment:
      - FLASK_APP=Feelog.py
    volumes:
      - .:/app
    command: gunicorn -b 0.0.0.0:5000 Feelog:app

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.17
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  esdata:
