version: "3.8"

services:
  flaskapp:
    build: .
    container_name: flaskapp
    ports:
      - "5000:5000"
    depends_on:
      elasticsearch:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - FLASK_APP=wsgi.py
    volumes:
      - .:/app
    networks:
      - feelog-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.17
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - feelog-net
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    mem_limit: 1g
    

volumes:
  esdata:

networks:
  feelog-net:
