"""add tag to post

Revision ID: 25552bcfac91
Revises: 961503d94bab
Create Date: 2025-06-22 13:40:29.320015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25552bcfac91'
down_revision = '961503d94bab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag', sa.String(length=30), nullable=True))
        batch_op.create_index(batch_op.f('ix_post_tag'), ['tag'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_tag'))
        batch_op.drop_column('tag')

    # ### end Alembic commands ###
