"""admin role

Revision ID: 30110b5d93bc
Revises: 53f40f0ebd8d
Create Date: 2025-06-28 15:42:51.573972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30110b5d93bc'
down_revision = '53f40f0ebd8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
