"""Added pic column to Post modell

Revision ID: 8100dbcdaa6a
Revises: 34e9e097094a
Create Date: 2025-06-26 23:21:26.877713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8100dbcdaa6a'
down_revision = '34e9e097094a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pic', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('pic')

    # ### end Alembic commands ###
