"""banned_new

Revision ID: df90e4cb4795
Revises: 85f3f9580f8e
Create Date: 2025-06-28 18:04:30.423529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df90e4cb4795'
down_revision = '85f3f9580f8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_banned',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_banned',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
