"""Add cheers and boos to Post

Revision ID: f638c7c240bc
Revises: 25552bcfac91
Create Date: 2025-06-25 17:39:29.162291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f638c7c240bc'
down_revision = '25552bcfac91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cheers', sa.Integer(), nullable=False,server_default='0'))
        batch_op.add_column(sa.Column('boos', sa.Integer(), nullable=False,server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('boos')
        batch_op.drop_column('cheers')

    # ### end Alembic commands ###
